#!/bin/bash
#SBATCH --account OZTIRELI-SL2-GPU
#SBATCH -p ampere
#SBATCH --nodes 1
#SBATCH --gres=gpu:1
#SBATCH --time=36:00:00
#SBATCH --mail-type=NONE

. /etc/profile.d/modules.sh
module unload cuda/8.0
module unload rhel8/default-gpu
module unload gcc-5.4.0-gcc-4.8.5-fis24gg
module load gcc-7.2.0-gcc-4.8.5-pqn7o2k
source /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/miniconda3-4.7.12.1-rmuek6r3f6p3v6fdj7o2klyzta3qhslh/etc/profile.d/conda.sh
conda activate mvsnerf1
#! module purge
#! module load rhel8/default-amp
#! module load cuda/11.1 cudnn/8.0_cuda-11.1
#! source /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/miniconda3-4.7.12.1-rmuek6r3f6p3v6fdj7o2klyzta3qhslh/etc/profile.d/conda.sh
#! conda activate nex
#! python train_gs_mvs_nerf_finetuning_pl.py --dataset_name dtu_ft_gs --datadir /rds/user/hl589/hpc-work/data/dtu_example/scan114 --expname scan114_gs-mvsnerf-ft-vo0.00005-model0.0001-op0.05-scale0.01-ds0.01 --model_lr 0.0001 --volume_lr 0.00005 --with_rgb_loss  --batch_size 1 --num_epochs 60000  --imgScale_test 1.0   --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 10 --net_type v3 --netchunk 100000
#! python sanity_check.py --dataset_name dtu_ft_gs --datadir /rds/user/hl589/hpc-work/data/dtu_example/scan114 --expname checkgs-0.0005 --with_rgb_loss  --batch_size 1 --num_epochs 300000  --imgScale_test 1.0   --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 10 --net_type v3 --netchunk 100000

#python train_gs_mvs_nerf_finetuning_pl.py --dataset_name dtu_ft_gs --datadir /rds/user/hl589/hpc-work/data/dtu_example/scan114 --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname singleimage_nopointloss_multi_volume_scan114_gs-mvsnerf-ft-lr1e-4 --num_epochs 60000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 10 --net_type v3 --netchunk 100000 
#python train_gs_mvs_nerf_finetuning_pl.py --dataset_name dtu_ft_gs --datadir /rds/user/hl589/hpc-work/data/dtu_example/scan114 --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname singleimage_pointloss_multi_volume_scan114_gs-mvsnerf-ft-lr1e-4 --withpointrgbloss --num_epochs 60000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 10 --net_type v3 --netchunk 100000 
# python train_gs_mvs_nerf_finetuning_pl.py --dataset_name dtu_ft_gs --datadir /rds/user/hl589/hpc-work/data/dtu_example/scan114 --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname singlescene_nopointloss_multi_volume_scan114_gs-mvsnerf-ft-lr1e-4 --increaseactivation_step 300000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 50 --net_type v3 --netchunk 100000 
#python train_gs_mvs_nerf_finetuning_pl.py --dataset_name dtu_ft_gs --datadir /rds/user/hl589/hpc-work/data/dtu_example/scan114 --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname singlescene_pointloss_multi_volume_scan114_gs-mvsnerf-ft-lr1e-4 --withpointrgbloss --increaseactivation_step 300000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 50 --net_type v3 --netchunk 100000 

# python train_gs_mvs_nerf_finetuning_pl.py --dataset_name dtu_ft_gs --datadir /rds/user/hl589/hpc-work/data/dtu_example/scan114 --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname singlescene_nopointloss_grow1w_multi_volume_scan114_gs-mvsnerf-ft-lr1e-4 --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 50 --net_type v3 --netchunk 100000 

# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_nopointloss_grow1w_multi_volume_lr1e-4 --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 50 --net_type v3 --netchunk 100000 
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_onescale_point10_nopointloss_grow1w_multi_volume_lr1e-4 --singlescale --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000 

# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname newversion_reso192_dtu_gs_withmask_onescale0.005_point10_nopointloss_grow1w_multi_volume_lr1e-4 --singlescale --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000 --depth_res 192

#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname newversion_reso192_dtu_gs_withmask_onescale0.001_point10_nopointloss_grow1w_multi_volume_lr1e-4 --singlescale --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000 --depth_res 192
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname newversion_reso192_dtu_gs_withmask_multiscale0.001_point10_nopointloss_grow1w_multi_volume_lr1e-4  --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000 --depth_res 192
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname newversion_dtu_gs_withmask_onescale0.003_point400_nopointloss_grow1w_multi_volume_lr1e-4 --singlescale  --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname newversion_dtu_gs_withmask_onescale0.001_point400_nopointloss_grow1w_multi_volume_lr1e-4 --singlescale  --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname newversion_dtu_gs_withmask_onescale0.003_point10_nopointloss_grow1w_multi_volume_lr1e-4 --singlescale  --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname newversion_dtu_gs_withmask_onescale0.005_0.02_point400_nopointloss_grow1w_multi_volume_lr1e-4 --singlescale --decay_scale 0.02 --increaseactivation_step 10000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000


# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_onescale0.003_point10_nopointloss_sh0multi_volume_lr1e-4 --singlescale --decay_scale 0.003 --increaseactivation_step 30000000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_multiscale0.003_point10_nopointloss_sh0multi_volume_lr1e-4 --decay_scale 0.003 --increaseactivation_step 30000000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_onescale0.005_point10_nopointloss_sh0multi_volume_lr1e-4 --singlescale --decay_scale 0.005 --increaseactivation_step 30000000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_multiscale0.005_point10_nopointloss_sh0multi_volume_lr1e-4  --decay_scale 0.005 --increaseactivation_step 30000000 --num_epochs 10000  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 5000 --net_type v3 --netchunk 100000


# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_multiscale0.005_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4   --decay_scale 0.005 --increaseactivation_step 30000000 --num_epochs 10  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 10 --net_type v3 --netchunk 100000
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_multiscale0.003_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4   --decay_scale 0.003 --increaseactivation_step 30000000 --num_epochs 10  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 10 --net_type v3 --netchunk 100000
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_multiscale0.005_point10_randomviews_nopointloss_sh0single_volume_lr1e-4   --decay_scale 0.005 --increaseactivation_step 30000000 --num_epochs 10  --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 10 --net_type v3 --netchunk 100000
# python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_multiscale0.005_point10_randomviews_nopointloss_sh0single_volume_lr1e-4_numview9_32   --decay_scale 0.005 --increaseactivation_step 30000000 --num_epochs 10  --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --N_vis 6 --net_type v3 --netchunk 100000 --n_views 9 --volume_feat_outputdim 32


#python train_mvs_nerf_pl.py --dataset_name dtu --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_3_wdepth_wviewdir --num_epochs 10  --with_depth --use_viewdirs --batch_size 1024
#python train_mvs_nerf_pl.py --dataset_name dtu --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_9_wdepth_wviewdir --num_epochs 10 --use_viewdirs --batch_size 1024  --with_depth --n_views 9 #--volume_feat_outputdim 32
#python train_mvs_nerf_pl.py --dataset_name dtu --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_9_32_wdepth_wviewdirs --num_epochs 10 --batch_size 1024  --with_depth --n_views 9 --volume_feat_outputdim 32 --use_viewdirs

#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname 7lc_dtu_gs_withmask_multiscale0.003_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4_numview6_8   --decay_scale 0.005 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --N_vis 12 --net_type v3 --netchunk 100000 --n_views 6
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname 7lc_dtu_gs_withmask_multiscale0.003_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4   --decay_scale 0.003 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 12 --net_type v3 --netchunk 100000
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname 7lc_dtu_gs_withmask_multiscale0.002_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4   --decay_scale 0.002 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 12 --net_type v3 --netchunk 100000
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname wviewdirs_7lc_dtu_gs_withmask_multiscale0.003_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4   --decay_scale 0.003 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 12 --net_type v3 --netchunk 100000  --use_viewdirs
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname wviewdirs_7lc_dtu_gs_withmask_multiscale0.002_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4   --decay_scale 0.002 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 12 --net_type v3 --netchunk 100000  --use_viewdirs
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname dtu_gs_withmask_multiscale0.005_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4_numview6_32   --decay_scale 0.005 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --N_vis 5000 --net_type v3 --netchunk 100000 --n_views 6 --volume_feat_outputdim 32


#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname wviewdirs_7lc_dtu_gs_withmask_multiscale0.003_point10_randomviews_nopointloss_sh0multi_volume_lr1e-3   --decay_scale 0.003 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 12 --net_type v3 --netchunk 100000  --use_viewdirs
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname wviewdirs_7lc_dtu_gs_withmask_multiscale0.003_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4_256   --decay_scale 0.003 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 12 --net_type v3 --netchunk 100000  --use_viewdirs --depth_res 256
python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname wviewdirs_7lc_dtu_gs_withmask_multiscale0.03_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4_scale0.05   --decay_scale 0.03 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 12 --net_type v3 --netchunk 100000  --use_viewdirs --depth_res 128 --pt_folder Pointclouds10_scale0.05
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp --expname wviewdirs_7lc_dtu_gs_withmask_multiscale0.003_point10_randomviews_nopointloss_sh0multi_volume_lr1e-4_256_singlescene   --decay_scale 0.003 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --ckpt ./ckpts/mvsnerf-v0.tar --N_vis 12 --net_type v3 --netchunk 100000  --use_viewdirs --depth_res 256 --single_scene


# example command to train with transmvsnet pts
#python train_gs_mvs_nerf_pl.py --dataset_name dtu_gs --datadir /rds/project/rds-JDeuXlFW9KE/data/dtu \
#    --savedir /rds/project/rds-JDeuXlFW9KE/hanxue_project/mvsnerf_exp \
#    --expname pointclouds5_transmvs_photo_ply   \
#    --decay_scale 0.005 --increaseactivation_step 30000000 --num_epochs 12  --multi_volume --lrate 0.0001  \
#    --imgScale_test 1.0   --with_rgb_loss  --batch_size 1 --pad 24 --N_vis 5000 --net_type v3 \
#    --netchunk 100000 --n_views 6 --volume_feat_outputdim 32 \
#    --pt_folder pointclouds5_transmvs_photo_ply --pt_downsample 2




